#!/bin/sh
#
# ~/bin/acp
#
# Andrew Antle - http://antlechrist.org/
#

#
# Source the configuration file.
#
. ~/etc/acp.conf

#
# `-a` pulls $USER's subdomain
# `-s` pushes $USER's subdomain
# `-d` pulls the entire site
# `-f` pushes the entire site
#
case "$1" in
-a)
	$RSYNC -avz --delete -e "$SSH -p $PORT" \
		$RUSER@$RHOST:$DIR/$USER/ $DIR/$USER/
	;;
-s)
	$RSYNC -avz --delete -e "$SSH -p $PORT" \
		$DIR/$USER/ $RUSER@$RHOST:$DIR/$USER/
	;;
-d)
	$RSYNC -avz --delete -e "$SSH -p $PORT" \
		$RUSER@$RHOST:$DIR/ $DIR/
	;;
-f)
	$RSYNC -avz --delete -e "$SSH -p $PORT" \
		$DIR/ $RUSER@$RHOST:$DIR/
	;;
*)
	echo "usage: `basename $0` {-a|-s|-d|-f}"
	;;
esac
