#!/bin/sh
#
# ~/bin/apic
# 
# Andrew Antle - http://antlechrist.org
#

BACKUPDIR=/mnt/sdc1/backups/folder
CONVERT=/usr/bin/convert
ID3=/usr/bin/eyeD3
IMAGE=folder.jpg
TAGOPTIONS="--add-image=$IMAGE:FRONT_COVER"

set -e

do_apic() {
	$ID3 $TAGOPTIONS *.mp3
}

do_convert() {
	$CONVERT $IMAGE -resize '200x200!' $IMAGE.new
	mv $IMAGE $$-$IMAGE
	mv $IMAGE.new $IMAGE
	ls -lh
}

do_id3() {
	$ID3 *.mp3

	for i in *.jpg; do
		mv -i $i $BACKUPDIR/$i.$$
	done

	ls -lh
}

if [ ! -f $IMAGE ]; then
	echo "the album art must have the file name: $IMAGE"
	exit 1
fi

if [ ! -x $CONVERT ] || [ ! -x $ID3 ]; then
	echo "`basename $ID3` and imagemagick are required"
	exit 1
fi

do_convert
do_apic
do_id3
