#!/bin/sh
#
# ~/bin/apic
# Andrew Antle - http://antlechrist.org

CONVERT_IMG=/usr/bin/convert
IMG=folder.jpg

set -e

[ -f $IMG ] || \
(echo "the album art must have the file name: $IMG" && exit 1)

[ -x $CONV_IMG ] || \
(echo "`basename $CONVERT_IMG` from imagemagick required" && exit 1)

$CONVERT_IMG $IMG -resize '200x200!' $IMG.new
mv $IMG $$-$IMG
mv $IMG.new $IMG

eyeD3 --add-image=$IMG:FRONT_COVER *.mp3

for i in *.jpg; do
	mv $i $backups/folder/$i.$$
done
