#!/bin/sh
#
# ~/bin/shome; sync home
# Andrew Antle - http://antlechrist.org

RSYNC=/usr/bin/rsync
DEST=$backups/$USER
EXCLUDE_FILE=~/.exclude

set -e

cd

if test ! -d $DEST; then
	mkdir -p $DEST
fi

sudo $RSYNC -avz --delete --exclude-from=$EXCLUDE_FILE $HOME/ $DEST/
