#!/bin/sh
#
# ~/bin/shome
#
# Andrew Antle - http://antlechrist.org
#

RSYNC=/usr/bin/rsync
DEST=/mnt/sdc1/backups/$USER

set -e

cd

if test ! -d $DEST; then
	mkdir -p $DEST
fi

sudo $RSYNC -avz --delete $HOME/ $DEST/
