#!/bin/sh
#
# ~/bin/wax
# Andrew Antle - http://antlechrist.org/
#
# Wax on, wax off.
# Dependencies: mutagen

FRAMES1="COMM,MCDI,PCNT,PRIV,TBPM,TCOM,TCON,TDRL,TDTG,TENC,TIPL"
FRAMES2="TIT1,TKEY,TLAN,TLEN,TPE2,TPOS,TPUB,TSSE,TXXX,UFID,WCOM,WXXX"
TOTAL="$FRAMES1,$FRAMES2"

mid3v2 --delete-frames=$TOTAL *.mp3

rm AlbumArt* \
   ZuneArt* \
   *.ini \
   *.db \
   *.m3u \
   *.nfo \
   *.sfv \
   *.mht \
   .directory \
   .folder.png 2>/dev/null

mv Folder.jpg folder.jpg 2>/dev/null
